### ISSUE TITLE
不支持python2.7+

### ISSUE THREAD

**Issue by dev-techmoe** [tencentyun/cos-python-sdk#15]
估计诸位心里也是知道的吧。  
**求更新**，辛苦

**Comment by wucheng** [comment]
python sdk推荐运行在python 2.7.x版本，支持python 2.7

**Comment by rainyear** [comment]
何时支持3.5？

**Comment by dev-techmoe** [comment]
@rainyear 尝试自己2to3然后再改改吧。。我就是这样做的  
自己改的太丑就不发出来了。。
