### ISSUE TITLE
secretKey 配置问题

### ISSUE THREAD

**Issue by haipome** [tencentyun/cos-python-sdk#9]
pip install qcloud_cos 后，文件已经 copy 到了系统目录里面，没办法再去修改 conf.py 了。多个项目也无法使用不同的配置。能否改变一下配置的方式？比如用 class 实现？

**Comment by cliffordsun** [comment]
说明中丢了一项，但是例子中给出了，不修改conf.py可以通过构造函数设置key和id。
但是要注意一下这个key和id是全局变量。这一点确实存在一些弊端，我们后续会做修改。谢谢反馈。
